import * as functions from 'firebase-functions';
const cors = require('cors')({origin: true});
const Ravepay = require('flutterwave-node-v3');
const rave = new Ravepay("FLWPUBK-df9a894a4de44dccbfe1898f62384e1c-X", 
"FLWSECK-d64dec53e789c84d460191a2731817b4-X", true);

export const pay  = functions.https.onRequest(function (request, response) {
    cors(request, response, () => {
        const mobile_money = async () => {
            try {
                const payload_response: any = request.body;
                const payload = {
                    "tx_ref": "MC-"+ Math.floor(Math.random() * 1000000000),
                    "amount": payload_response['amount'],
                    "email": payload_response['email'],
                    "phone_number": payload_response['telephone'],
                    "currency": "UGX",
                    "fullname": payload_response['fullName'],
                    "redirect_url": "https://app.filetax.live",
                    "voucher": Math.floor(Math.random() * 1000000000), //This is the voucher code generated by the customer. It is meant to be passed in the initial charge request. (only for Vodafone cash)
                    "network": payload_response['line']
                }
         
               const response_flutterwave =  await rave.MobileMoney.uganda(payload);
               response.end();
               console.log(response_flutterwave);
            } catch (error) {
                console.log(error);
                response.send({message: "something went wrong", error: error});
            }
        };
        mobile_money();
    });
});